export const DISCORD_INVITE_URL =
	process.env.NEXT_PUBLIC_DISCORD_INVITE_URL ||
	'https://discord.gg/X9ezaj8vEY';

export const DISCORD_SUPPORT_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_SUPPORT_CHANNEL_URL ||
	DISCORD_INVITE_URL;

export const DISCORD_STORE_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_STORE_CHANNEL_URL ||
	DISCORD_SUPPORT_CHANNEL_URL;

export const DISCORD_DAYZ_CLOTHING_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_DAYZ_CLOTHING_CHANNEL_URL ||
	DISCORD_STORE_CHANNEL_URL;

export const DISCORD_DAYZ_VEHICLES_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_DAYZ_VEHICLES_CHANNEL_URL ||
	DISCORD_STORE_CHANNEL_URL;

export const DISCORD_ITEMS_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_ITEMS_CHANNEL_URL ||
	DISCORD_STORE_CHANNEL_URL;

export const DISCORD_CUSTOM_BASES_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_CUSTOM_BASES_CHANNEL_URL ||
	DISCORD_STORE_CHANNEL_URL;

export const DISCORD_SCIFI_GEAR_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_SCIFI_GEAR_CHANNEL_URL ||
	DISCORD_STORE_CHANNEL_URL;

export const DISCORD_SCIFI_BASE_ITEMS_CHANNEL_URL =
	process.env.NEXT_PUBLIC_DISCORD_SCIFI_BASE_ITEMS_CHANNEL_URL ||
	DISCORD_STORE_CHANNEL_URL;
